### ISSUE TITLE
Code generated from BooleanPrimitives.crml file doesn't compile/simulate with OMEdit

### ISSUE THREAD

**Issue by audrey-jardin** [lenaRB/crml-compiler#13]
See the generated Modelica code:
[BooleanPrimitives.zip](https://github.com/lenaRB/crml-compiler/files/10245308/BooleanPrimitives.zip)

and the error message from OMEdit:

![image](https://user-images.githubusercontent.com/57661590/208086956-3fb1a04b-338a-4add-ba17-4f0a08652664.png)

**Comment by audrey-jardin** [comment]
Note: It seems that some dependencies remain between CRMLtoModelica.mo and CRML.mo.

**Comment by audrey-jardin** [comment]
There is no more dependency between CRMLtoModelica.mo and CRML.mo.
But example BooleanPrimitives.crml still doesn't simulate -> there is typo during the translation. @lenaRB 
The correct name of the filter function is `mul4` (and not `mul2x4`).
![image](https://user-images.githubusercontent.com/57661590/213031537-4e259024-e479-478f-b380-077b13dbc1a5.png)

**Comment by lenaRB** [comment]
This should now be fixed, the correct operator is generated and the file example should work.
