### ISSUE TITLE
Use of keyword 'new' in CRML

### ISSUE THREAD

**Issue by lenaRB** [lenaRB/crml-compiler#14]
There is no keyword new in [BooleanConstructors.crml](src/test/resources/testFiles/spec-doc-examples/BooleanConstructors.crml)
It would make it more readable and easy to parse if conversions used "new", but we can discuss it of course.

**Comment by audrey-jardin** [comment]
You mean that a clearer syntax would be:
`Boolean b4 is undefined;lock c1 is external;
 Boolean b5 is new Boolean c1;`

**Comment by audrey-jardin** [comment]
Pull request #16 should fix the issue (addition of the "new" keyword in the CRML examples).
