### ISSUE TITLE
the use of new

### ISSUE THREAD

**Issue by lenaRB** [lenaRB/crml-compiler#52]
why is 'new' not used when creating a new period? I am still a bit fuzzy on when we use new and when it is implicit. Is it when we use it for type conversion? Like new Clock my_boolean?

**Comment by audrey-jardin** [comment]
@lenaRB : yes it is used when type conversion is needed

**Comment by audrey-jardin** [comment]
(I tried to update the unit tests with that use of 'new' but I haven't finished yet - I'd prefered to focus on ETL)

**Comment by lenaRB** [comment]
New is now the default way to do type conversion, eg: Boolean -> Event and is supported in the compiler
