### ISSUE TITLE
verifying test results

### ISSUE THREAD

**Issue by lenaRB** [lenaRB/crml-compiler#56]
For some tests, especially ones without external variables it would be easiest to have the expected value as some kind of annotation instead of a whole reference file with results, because we only care about the value of the requirement for example. 

Then we should just have an annotation for that in the relevant tests? var = b, expectedResult = true
@adrpo, @audrey-jardin  what do you think?

**Comment by audrey-jardin** [comment]
@lenaRB , @adrpo : I'm not sure to understand what you suggest. 
Please provide an example so I can see if it is relevant and if I can provide such format.
My first guess is that, except maybe for Boolean4 unit tests, it wouldn't be so easy in general as values can be time-varying.

**Comment by lenaRB** [comment]
As discussed today, we keep with reference files for all test cases for simplicity.
