### ISSUE TITLE
Solve problem for opening CRML.mo in OpenModelica

### ISSUE THREAD

**Issue by audrey-jardin** [lenaRB/crml-compiler#64]
When loading CRML.mo library, error message appears and nothing happens (probably due to dependencies to other libraries such as Modelica 3.2.2 and Modelica_StateGraph.

![image](https://github.com/lenaRB/crml-compiler/assets/57661590/0081946c-6b75-4444-8b1d-32524ffba540)

**Comment by adrpo** [comment]
This is now fixed by @audrey-jardin via PR #83 by porting all libraries to MSL 4.0.0.
