### ISSUE TITLE
Wrong status in test_report.html

### ISSUE THREAD

**Issue by audrey-jardin** [lenaRB/crml-compiler#71]
Status reported in test_report.html is not correct for some of the tests.
See in particular CheckOver example below that is mentioned as successful although no verification model has been provided (and hence no simulation could be verified).

![image](https://github.com/lenaRB/crml-compiler/assets/57661590/2a484620-489e-40d4-bff8-551adf6f738e)

**Comment by lenaRB** [comment]
This is now fixed, tests fail if there is no verification model.
